apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-r-app
  namespace: swish-proj
  labels:
    app: python-r-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-r-app
  template:
    metadata:
      labels:
        app: python-r-app
    spec:
      containers:
        - name: python-r-container
          image: 0l4bode/swish-devsecops-proj:2.2
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 30; done"]
          ports:
            - containerPort: 8080
