apiVersion: v1
kind: Service
metadata:
  name: python-r-app-service
  namespace: swish-proj
spec:
  selector:
    app: python-r-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
