name: Multi-Environment Deployment Pipeline

on:
  workflow_dispatch: # Triggered by the Python-R Swish Proj Pipeline
    inputs:
      docker_image:
        description: "Docker image to deploy"
        required: true

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development
        run: |
          echo "Deploying to Development Environment"
          docker run -d \
            --name dev-env-${{ github.run_id }} \
            --cpus=1 \
            --memory=512Mi \
            ${{ github.event.inputs.docker_image }}

  deploy-uat:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Deploy to UAT
        run: |
          echo "Deploying to UAT Environment"
          docker run -d \
            --name uat-env-${{ github.run_id }} \
            --cpus=2 \
            --memory=1Gi \
            ${{ github.event.inputs.docker_image }}

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-uat
    environment:
      name: production # Use GitHub environment for approval
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to Production Environment"
          docker run -d \
            --name prod-env-${{ github.run_id }} \
            --cpus=4 \
            --memory=2Gi \
            ${{ github.event.inputs.docker_image }}
