name: Python-R Swish Proj Pipeline

on:
  push:
    branches:
      - main
    paths:
        - "Dockerfile"          # Trigger for Dockerfile changes
        - "app.py"              # Trigger for app changes
  pull_request:
    branches:
      - main
    paths:
        - "Dockerfile"          # Trigger for Dockerfile changes
        - "app.py"              # Trigger for app changes
  workflow_dispatch:                 # Allows manual triggering of the pipeline

env:
  DOCKER_IMAGE: 0l4bode/swish-devsecops-proj

jobs:
  # Docker Build and Push Job
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'Dockerfile') || 
      contains(github.event.head_commit.message, 'app.py') || 
      github.event_name == 'workflow_dispatch'

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Login
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_IMAGE:${{ github.sha }} .
          docker tag $DOCKER_IMAGE:${{ github.sha }} $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:${{ github.sha }}
          docker push $DOCKER_IMAGE:latest

  
